[tool.poetry]
name = "nemcore"
version = "0.1.0"
description = "NetEase Cloud Music ApiClient extract from NetEase-MusicBox"
authors = ["weak_ptr <weak_ptr@163.com>"]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.22"
requests-cache = "^0.5.2"
six = "^1.12"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
