[tool.poetry]
name = "nemcore"
version = "0.1.2"
description = "NetEase Cloud Music ApiClient extracted from NetEase-MusicBox"
authors = ["weak_ptr <weak_ptr@163.com>"]
license = 'MIT'
readme = "README.md"
homepage = "https://github.com/nnnewb/NEMCore"
keywords = ["netease","sdk","netease cloudmusic"]
classifier = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Natural Language :: Chinese (Simplified)",
    "Topic :: Software Development :: Libraries",
]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.22"
requests-cache = "^0.5.2"
six = "^1.12"
pycryptodome = "^3.9"
pycryptodomex = "^3.9"
toml = "^0.10.0"
cachetools = "^3.1"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
flake8 = "^3.7"
flake8-bugbear = "^19.8"
yapf = "^0.28.0"
isort = "^4.3"
pytest-cov = "^2.7"
pytest-dotenv = "^0.4.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
